//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Continent { get; set; }
        public Nullable<float> SurfaceArea { get; set; }
        public Nullable<float> Population { get; set; }
        public Nullable<float> LifeExpectancy { get; set; }
        public Nullable<float> GNP { get; set; }
        public string HeadOfState { get; set; }
        public int ID { get; set; }
    }
}
